#!/bin/bash

# Quick deployment guide
echo "🚀 PrepWisely Backend Deployment Guide"
echo ""
echo "Prerequisites:"
echo "  - AWS CLI configured with credentials"
echo "  - AWS SAM CLI installed (for API Gateway deployment)"
echo "  - Node.js installed"
echo ""
echo "Steps:"
echo ""
echo "1. Deploy DynamoDB tables and Lambda functions:"
echo "   ./deploy-backend.sh"
echo ""
echo "2. Get your API endpoint from the output"
echo ""
echo "3. Update src/app/config/api-config.ts with your API endpoint"
echo ""
echo "4. Seed sample questions:"
echo "   cd scripts && npm install && node seed-questions.js"
echo ""
echo "5. Build and deploy frontend:"
echo "   npm run build"
echo "   ./aws-manager.sh deploy"
echo ""
echo "Note: The backend uses:"
echo "  - DynamoDB for data storage"
echo "  - Lambda for API logic"
echo "  - API Gateway for REST endpoints"
echo "  - Cognito for authentication"
echo ""
