#!/bin/bash

echo "🧪 Testing Certificate Generation System"
echo ""
echo "⚠️  This test requires:"
echo "   1. A valid Cognito access token"
echo "   2. User to be logged in"
echo ""
echo "To test manually:"
echo "1. Log in to https://nestedcerts.com"
echo "2. Complete all quizzes for a certification"
echo "3. Click 'Download Certificate' button"
echo ""
echo "Expected behavior:"
echo "✓ Button appears only when all 32 quizzes/exams are completed"
echo "✓ Clicking button generates PDF with user's name from Cognito"
echo "✓ PDF downloads automatically"
echo "✓ Certificate includes:"
echo "  - User's full name (from Cognito 'name' attribute)"
echo "  - Certification title"
echo "  - Completion date"
echo "  - Unique serial number (NC-{CERT}-{TIMESTAMP})"
echo ""
echo "📋 System Components:"
echo "✓ Lambda: nestedcerts-certificate-generator-prod"
echo "✓ S3 Bucket: nestedcerts-certificates-prod-947977408385"
echo "✓ API: https://yxa4lhwakg.execute-api.ap-southeast-2.amazonaws.com/prod/generate"
echo "✓ Template: s3://prepwisely-app-prod-947977408385/Certificate/nestedcerts_simple_colored_certificate.pdf"
echo ""
echo "🔍 To check Lambda logs:"
echo "aws logs tail /aws/lambda/nestedcerts-certificate-generator-prod --follow --region ap-southeast-2"
echo ""
echo "🔍 To check generated certificates:"
echo "aws s3 ls s3://nestedcerts-certificates-prod-947977408385/certificates/ --recursive --region ap-southeast-2"
