AWSTemplateFormatVersion: '2010-09-09'
Description: 'PrepWisely CloudFront Distribution Stack'

Parameters:
  S3StackName:
    Type: String
    Default: prepwisely-s3-stack
    Description: Name of the S3 stack to import bucket from
  
  Environment:
    Type: String
    Default: prod
    AllowedValues: [dev, staging, prod]
    Description: Environment name

Resources:
  # CloudFront Origin Access Control
  OriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub 'PrepWisely-${Environment}-OAC'
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
        Description: !Sub 'PrepWisely ${Environment} Origin Access Control'

  # Cache Policy for SEO files (robots.txt, sitemap.xml)
  SEOFilesCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: !Sub 'PrepWisely-${Environment}-SEO-Files'
        Comment: 'Cache policy for robots.txt and sitemap.xml with 5 min TTL'
        DefaultTTL: 300
        MaxTTL: 300
        MinTTL: 300
        ParametersInCacheKeyAndForwardedToOrigin:
          EnableAcceptEncodingGzip: true
          EnableAcceptEncodingBrotli: true
          QueryStringsConfig:
            QueryStringBehavior: none
          HeadersConfig:
            HeaderBehavior: none
          CookiesConfig:
            CookieBehavior: none

  # Response Headers Policy for SEO files
  SEOFilesResponseHeadersPolicy:
    Type: AWS::CloudFront::ResponseHeadersPolicy
    Properties:
      ResponseHeadersPolicyConfig:
        Name: !Sub 'PrepWisely-${Environment}-SEO-Headers'
        Comment: 'Response headers for SEO files with short cache'
        CustomHeadersConfig:
          Items:
            - Header: Cache-Control
              Value: 'public, max-age=300'
              Override: true

  # CloudFront Distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: !Sub 'PrepWisely ${Environment} Distribution'
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        PriceClass: PriceClass_100
        
        Origins:
          - Id: S3Origin
            DomainName: 
              Fn::ImportValue: !Sub '${S3StackName}-BucketDomainName'
            S3OriginConfig:
              OriginAccessIdentity: ''
            OriginAccessControlId: !Ref OriginAccessControl
        
        # Cache behaviors for SEO files
        CacheBehaviors:
          - PathPattern: /robots.txt
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: [GET, HEAD]
            CachedMethods: [GET, HEAD]
            Compress: false
            CachePolicyId: !Ref SEOFilesCachePolicy
            ResponseHeadersPolicyId: !Ref SEOFilesResponseHeadersPolicy
          - PathPattern: /sitemap.xml
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: [GET, HEAD]
            CachedMethods: [GET, HEAD]
            Compress: false
            CachePolicyId: !Ref SEOFilesCachePolicy
            ResponseHeadersPolicyId: !Ref SEOFilesResponseHeadersPolicy
        
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD, OPTIONS]
          CachedMethods: [GET, HEAD]
          Compress: true
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad # Managed-CachingOptimized
          OriginRequestPolicyId: 88a5eaf4-2fd4-4709-b370-b4c650ea3fcf # Managed-CORS-S3Origin
        
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 300
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 300
      
      Tags:
        - Key: Project
          Value: PrepWisely
        - Key: Environment
          Value: !Ref Environment

Outputs:
  DistributionId:
    Description: 'CloudFront Distribution ID'
    Value: !Ref CloudFrontDistribution
    Export:
      Name: !Sub '${AWS::StackName}-DistributionId'
  
  DistributionDomainName:
    Description: 'CloudFront Distribution Domain Name'
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: !Sub '${AWS::StackName}-DomainName'
  
  WebsiteURL:
    Description: 'Website URL'
    Value: !Sub 'https://${CloudFrontDistribution.DomainName}'
    Export:
      Name: !Sub '${AWS::StackName}-WebsiteURL'
