AWSTemplateFormatVersion: '2010-09-09'
Description: 'PrepWisely DynamoDB Tables'

Resources:
  # Users Table - Store user subscriptions and owned certifications
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: prepwisely-users
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Application
          Value: PrepWisely

  # Questions Table - Store all exam questions
  QuestionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: prepwisely-questions
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: questionId
          AttributeType: S
        - AttributeName: certId
          AttributeType: S
      KeySchema:
        - AttributeName: questionId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: certId-index
          KeySchema:
            - AttributeName: certId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Application
          Value: PrepWisely

  # User Progress Table - Track quiz completions and scores
  UserProgressTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: prepwisely-user-progress
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: certQuizId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: certQuizId
          KeyType: RANGE
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Application
          Value: PrepWisely

Outputs:
  UsersTableName:
    Description: Users table name
    Value: !Ref UsersTable
    Export:
      Name: PrepWisely-UsersTable
  
  UsersTableArn:
    Description: Users table ARN
    Value: !GetAtt UsersTable.Arn
    Export:
      Name: PrepWisely-UsersTableArn
  
  QuestionsTableName:
    Description: Questions table name
    Value: !Ref QuestionsTable
    Export:
      Name: PrepWisely-QuestionsTable
  
  QuestionsTableArn:
    Description: Questions table ARN
    Value: !GetAtt QuestionsTable.Arn
    Export:
      Name: PrepWisely-QuestionsTableArn
  
  UserProgressTableName:
    Description: User progress table name
    Value: !Ref UserProgressTable
    Export:
      Name: PrepWisely-UserProgressTable
  
  UserProgressTableArn:
    Description: User progress table ARN
    Value: !GetAtt UserProgressTable.Arn
    Export:
      Name: PrepWisely-UserProgressTableArn

