AWSTemplateFormatVersion: '2010-09-09'
Description: 'PrepWisely S3 Static Website Hosting Stack - Simple'

Parameters:
  BucketName:
    Type: String
    Default: prepwisely-app
    Description: Name for the S3 bucket (must be globally unique)
  
  Environment:
    Type: String
    Default: prod
    AllowedValues: [dev, staging, prod]
    Description: Environment name

Resources:
  # S3 Bucket for static website hosting
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${BucketName}-${Environment}-${AWS::AccountId}'
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Project
          Value: PrepWisely
        - Key: Environment
          Value: !Ref Environment

Outputs:
  BucketName:
    Description: 'S3 Bucket Name'
    Value: !Ref WebsiteBucket
    Export:
      Name: !Sub '${AWS::StackName}-BucketName'
  
  WebsiteURL:
    Description: 'S3 Website URL'
    Value: !GetAtt WebsiteBucket.WebsiteURL
    Export:
      Name: !Sub '${AWS::StackName}-WebsiteURL'
  
  BucketDomainName:
    Description: 'S3 Bucket Domain Name'
    Value: !GetAtt WebsiteBucket.DomainName
    Export:
      Name: !Sub '${AWS::StackName}-BucketDomainName'
